/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.baturinsky.tabletop;

public final class R {
    public static final class array {
        public static final int main_menu_entries=0x7f050000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int button=0x7f020000;
        public static final int buttonsel=0x7f020001;
        public static final int buttonw=0x7f020002;
        public static final int even_stripe=0x7f020004;
        public static final int gold_transparent=0x7f020008;
        public static final int icon=0x7f020003;
        public static final int metallic_gold=0x7f020007;
        public static final int odd_stripe=0x7f020005;
        public static final int office_green=0x7f020006;
        public static final int pale=0x7f02000b;
        public static final int red=0x7f02000a;
        public static final int white=0x7f020009;
    }
    public static final class id {
        public static final int cancel=0x7f080002;
        public static final int file_list=0x7f080004;
        public static final int file_name=0x7f080003;
        public static final int list=0x7f080000;
        public static final int menu=0x7f080006;
        public static final int ok=0x7f080001;
        public static final int text=0x7f080005;
    }
    public static final class layout {
        public static final int browser=0x7f030000;
        public static final int browser_big_line=0x7f030001;
        public static final int button=0x7f030002;
        public static final int button_small=0x7f030003;
        public static final int edit=0x7f030004;
        public static final int fields_edit=0x7f030005;
        public static final int files=0x7f030006;
        public static final int help=0x7f030007;
        public static final int intro=0x7f030008;
        public static final int list_item=0x7f030009;
        public static final int main=0x7f03000a;
        public static final int optionlist_item=0x7f03000b;
        public static final int small_white_text=0x7f03000c;
        public static final int table_layout=0x7f03000d;
    }
    public static final class raw {
        public static final int card_images=0x7f040000;
        public static final int cards=0x7f040001;
        public static final int chess=0x7f040002;
        public static final int chess_pieces=0x7f040003;
        public static final int chessboard=0x7f040004;
        public static final int dbinit=0x7f040005;
        public static final int dr_black=0x7f040006;
        public static final int dr_black2=0x7f040007;
        public static final int dr_white=0x7f040008;
        public static final int dr_white2=0x7f040009;
        public static final int draughts=0x7f04000a;
    }
    public static final class string {
        public static final int app_name=0x7f060000;
        public static final int cancel=0x7f060007;
        public static final int cant_delete_file=0x7f06001a;
        public static final int content_references=0x7f060001;
        public static final int delete=0x7f06001d;
        public static final int dir_change=0x7f06001c;
        public static final int dir_create=0x7f06001b;
        public static final int dir_create_confirm=0x7f060017;
        public static final int dir_delete_confirm=0x7f060018;
        public static final int fields_edit_title=0x7f06000b;
        public static final int file_not_selected=0x7f060020;
        public static final int filter=0x7f06001e;
        public static final int help_text=0x7f06000a;
        public static final int insert=0x7f060004;
        public static final int intro_title=0x7f060009;
        public static final int invite_friend=0x7f060021;
        public static final int invite_friend_wip=0x7f060022;
        public static final int license=0x7f060027;
        public static final int no_filter=0x7f06001f;
        public static final int ok=0x7f060003;
        public static final int play_chess=0x7f060024;
        public static final int play_draughts=0x7f060025;
        public static final int play_other_game=0x7f060023;
        public static final int query=0x7f060006;
        public static final int relative_layout_2_instructions=0x7f060002;
        public static final int relative_layout_cancel=0x7f060008;
        public static final int root=0x7f060005;
        public static final int show_license=0x7f060026;
        public static final int table_layout_6_export=0x7f060014;
        public static final int table_layout_6_export_shortcut=0x7f060015;
        public static final int table_layout_6_import=0x7f060013;
        public static final int table_layout_6_open=0x7f06000d;
        public static final int table_layout_6_open_shortcut=0x7f06000e;
        public static final int table_layout_6_quit=0x7f060016;
        public static final int table_layout_6_save=0x7f06000f;
        public static final int table_layout_6_save_as=0x7f060011;
        public static final int table_layout_6_save_as_shortcut=0x7f060012;
        public static final int table_layout_6_save_shortcut=0x7f060010;
        public static final int table_layout_6_x=0x7f06000c;
        public static final int type_dir_name=0x7f060019;
    }
    public static final class style {
        public static final int Button=0x7f070001;
        public static final int Poker=0x7f070000;
    }
}
